check50:
 # files:
  #- !exclude "hello.py"
  #- !exclude "bye.py"
  checks:
    Hooray!:
      - run: python3 hello.py # run python3 hello.py
        stdout: Happy World # expect Hello, world! in stdout
        exit: 0 # expect program to exit with exitcode 
    foo:
      - run: python3 bye.py # run python3 foo.py
        stdout: see ya later # expect see ya later in stdout
        exit: 0 # expect program to exit with exitcode 0
lab50: true
