check50:
  files:
 # - !include "hello.py"
  checks:
    happy world:
      - run: python3 hello.py # run python3 hello.py
        stdout: Happy World # expect Hello, world! in stdout
        exit: 0 # expect program to exit with exitcode 
lab50: true
